### ISSUE TITLE
Knot 2.0 compatibility

### ISSUE THREAD

**Issue by yarikdot** [tobru/puppet-knot#3]
I have started reworking this module to make it working with currently stable (by upstream) version 2.0.

Unfortunately I am not sure if I will be able to finish it due to problems with time. Anyway, I have commited my current changes to https://github.com/yarikdot/puppet-knot/tree/knot-2.0 and I will update it if there are any further changes.

**Comment by tobru** [comment]
Thanks, I'll look into it soon as I have it already on my todo list =)

**Comment by tobru** [comment]
working on it, but still a lot to do...

**Comment by tobru** [comment]
Configuration file writing works now. Todo before finished:
- Update docs (README and header)
- Update rspec tests
- Implement DNSSEC support
